=pod
Problem 2: Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
https://projecteuler.net/problem=2
=cut

use strict;

# Set ceiling to 4'000'000
my $fib_limit = 4000000;

# Initialize start numbers of fibonacci sequence
my @fib_init = (1, 2);

sub sum_even_fibonacci_numbers {
    my $aref = shift @_;
    my ($fib1, $fib2) = @$aref;
    my $fib_limit = shift @_;
    my $sum = 0;
     
    while ( $fib2 <= $fib_limit ) {
        if ( $fib2 % 2 == 0 ) {
            $sum += $fib2;
        }
        # Calculate next fibonacci number, and remember only the last two values
        ($fib1, $fib2) = ($fib2, ($fib1 + $fib2));
    }
    return $sum;
}

# When calling the function, make sure to pass a reference to the array (\@fib_init), and copy values from array inside function
print"Sum(90):        ".sum_even_fibonacci_numbers(\@fib_init, 90)."\n";
print"Sum(4'000'000): ".sum_even_fibonacci_numbers(\@fib_init, $fib_limit)."\n";
